// Generated by CoffeeScript 1.12.7
(function() {
  var favorites, portCtoB;

  favorites = [];

  $("#favoriteStation option").each(function() {
    var fav, scd;
    fav = JSON.parse($(this).val() || "{}");
    if (scd = fav.cd) {
      return favorites.push({
        scd: scd,
        place: fav.nm,
        alias: fav.nm,
        checked: true
      });
    }
  });

  portCtoB = chrome.extension.connect({
    name: "CtoB"
  });

  portCtoB.postMessage({
    command: "sendFavorites",
    favorites: favorites
  });

  $(window).unload(function() {
    return portCtoB.disconnect();
  });

}).call(this);
