// Generated by CoffeeScript 1.12.7
(function() {
  var doneScriptLoad, ref, run, tp, uid;

  uid = (ref = window.location.href.match(/[\\?&]uid=([^&#]*)/)) != null ? ref[1] : void 0;

  tp = chrome.extension.getBackgroundPage().window.tp;

  tp.activity = tp.getActivity(uid);

  tp.activity.uid = uid;

  if (tp.activity.startClassName !== "FavoriteNomapView") {
    $LAB.script("js/underscore-min.js").script("js/jquery-2.0.0.min.js").wait().script("js/backbone-min.js").script("js/jquery-ui-1.9.2.custom.min.js").script("css/facybox.js").script("js/application.js").script("https://maps.googleapis.com/maps/api/js?key=AIzaSyApuorSOF_bs5SLCz2IdhokQFZlC_ZoibM&callback=doneScriptLoad");
  } else {
    $LAB.script("js/underscore-min.js").script("js/jquery-2.0.0.min.js").wait().script("js/backbone-min.js").script("css/facybox.js").script("js/classesNomap.js").wait(function() {
      return doneScriptLoad();
    });
  }

  chrome.tabs.getSelected(null, function(tab) {
    return chrome.pageAction.show(tab.id);
  });

  chrome.runtime.onMessage.addListener(function(message, sender) {
    var centerAddress;
    if (message === "restart") {
      centerAddress = tp.activity.misc.centerAddress;
      tp.activity = tp.getActivity(uid);
      tp.activity.misc.centerAddress = centerAddress;
      appView.reset();
      delete appView;
      return run();
    }
  });

  run = function() {
    var startClassName;
    startClassName = (function() {
      switch (tp.activity.misc.tabid) {
        case tp.tabidScdSeach:
          if (tp.activity.misc.selectListOrder !== "S") {
            return "SearchStaOrderWalkController";
          } else {
            return "SearchStaController";
          }
          break;
        case tp.tabidFavorite:
          if (tp.activity.misc.checkMap) {
            return "FavMapController";
          } else {
            return "FavNomapController";
          }
      }
    })();
    window.appView = new tp[startClassName]({});
    return window.appView.run();
  };

  doneScriptLoad = function() {
    return jQuery(function() {
      return run();
    });
  };

}).call(this);
